//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleRoute
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int Distance { get; set; }
        public string Date { get; set; }
        public System.Guid Id { get; set; }
    }
}
